# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02f1b175e39c8b5e2a5199d9c565139c47593fb6a27a420432c69a79154c2c94307c9977d63d8c65898c0bd88c20a71a6c09bf9a6e3f302743ecd90d2acd8ff2

test:
  secret_key_base: 626c1be3d4eab215a9cf2bc4d92ca2a711b5b1012c939f46f468e72fe1e4e2e6643c47b50c081655f26ba7e5f84fddabee96af94388ebe19cf16c8e60f1e02af

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
